// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: private_location/v1/dns_monitor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNSMonitor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uri              string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Timeout          int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	DegradedAt       *int64                 `protobuf:"varint,4,opt,name=degraded_at,json=degradedAt,proto3,oneof" json:"degraded_at,omitempty"`
	Periodicity      string                 `protobuf:"bytes,5,opt,name=periodicity,proto3" json:"periodicity,omitempty"`
	Retry            int64                  `protobuf:"varint,6,opt,name=retry,proto3" json:"retry,omitempty"`
	RecordAssertions []*RecordAssertion     `protobuf:"bytes,13,rep,name=record_assertions,json=recordAssertions,proto3" json:"record_assertions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DNSMonitor) Reset() {
	*x = DNSMonitor{}
	mi := &file_private_location_v1_dns_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSMonitor) ProtoMessage() {}

func (x *DNSMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_dns_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSMonitor.ProtoReflect.Descriptor instead.
func (*DNSMonitor) Descriptor() ([]byte, []int) {
	return file_private_location_v1_dns_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *DNSMonitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DNSMonitor) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *DNSMonitor) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *DNSMonitor) GetDegradedAt() int64 {
	if x != nil && x.DegradedAt != nil {
		return *x.DegradedAt
	}
	return 0
}

func (x *DNSMonitor) GetPeriodicity() string {
	if x != nil {
		return x.Periodicity
	}
	return ""
}

func (x *DNSMonitor) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *DNSMonitor) GetRecordAssertions() []*RecordAssertion {
	if x != nil {
		return x.RecordAssertions
	}
	return nil
}

var File_private_location_v1_dns_monitor_proto protoreflect.FileDescriptor

const file_private_location_v1_dns_monitor_proto_rawDesc = "" +
	"\n" +
	"%private_location/v1/dns_monitor.proto\x12\x13private_location.v1\x1a$private_location/v1/assertions.proto\"\x89\x02\n" +
	"\n" +
	"DNSMonitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12$\n" +
	"\vdegraded_at\x18\x04 \x01(\x03H\x00R\n" +
	"degradedAt\x88\x01\x01\x12 \n" +
	"\vperiodicity\x18\x05 \x01(\tR\vperiodicity\x12\x14\n" +
	"\x05retry\x18\x06 \x01(\x03R\x05retry\x12Q\n" +
	"\x11record_assertions\x18\r \x03(\v2$.private_location.v1.RecordAssertionR\x10recordAssertionsB\x0e\n" +
	"\f_degraded_atBJZHgithub.com/openstatushq/openstatus/packages/proto/private_location/v1;v1b\x06proto3"

var (
	file_private_location_v1_dns_monitor_proto_rawDescOnce sync.Once
	file_private_location_v1_dns_monitor_proto_rawDescData []byte
)

func file_private_location_v1_dns_monitor_proto_rawDescGZIP() []byte {
	file_private_location_v1_dns_monitor_proto_rawDescOnce.Do(func() {
		file_private_location_v1_dns_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_private_location_v1_dns_monitor_proto_rawDesc), len(file_private_location_v1_dns_monitor_proto_rawDesc)))
	})
	return file_private_location_v1_dns_monitor_proto_rawDescData
}

var file_private_location_v1_dns_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_private_location_v1_dns_monitor_proto_goTypes = []any{
	(*DNSMonitor)(nil),      // 0: private_location.v1.DNSMonitor
	(*RecordAssertion)(nil), // 1: private_location.v1.RecordAssertion
}
var file_private_location_v1_dns_monitor_proto_depIdxs = []int32{
	1, // 0: private_location.v1.DNSMonitor.record_assertions:type_name -> private_location.v1.RecordAssertion
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_private_location_v1_dns_monitor_proto_init() }
func file_private_location_v1_dns_monitor_proto_init() {
	if File_private_location_v1_dns_monitor_proto != nil {
		return
	}
	file_private_location_v1_assertions_proto_init()
	file_private_location_v1_dns_monitor_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_private_location_v1_dns_monitor_proto_rawDesc), len(file_private_location_v1_dns_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_private_location_v1_dns_monitor_proto_goTypes,
		DependencyIndexes: file_private_location_v1_dns_monitor_proto_depIdxs,
		MessageInfos:      file_private_location_v1_dns_monitor_proto_msgTypes,
	}.Build()
	File_private_location_v1_dns_monitor_proto = out.File
	file_private_location_v1_dns_monitor_proto_goTypes = nil
	file_private_location_v1_dns_monitor_proto_depIdxs = nil
}
