// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: private_location/v1/otel.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Headers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Headers) Reset() {
	*x = Headers{}
	mi := &file_private_location_v1_otel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Headers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Headers) ProtoMessage() {}

func (x *Headers) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_otel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Headers.ProtoReflect.Descriptor instead.
func (*Headers) Descriptor() ([]byte, []int) {
	return file_private_location_v1_otel_proto_rawDescGZIP(), []int{0}
}

func (x *Headers) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Headers) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OtelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Headers       []*Headers             `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtelConfig) Reset() {
	*x = OtelConfig{}
	mi := &file_private_location_v1_otel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtelConfig) ProtoMessage() {}

func (x *OtelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_otel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtelConfig.ProtoReflect.Descriptor instead.
func (*OtelConfig) Descriptor() ([]byte, []int) {
	return file_private_location_v1_otel_proto_rawDescGZIP(), []int{1}
}

func (x *OtelConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OtelConfig) GetHeaders() []*Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_private_location_v1_otel_proto protoreflect.FileDescriptor

const file_private_location_v1_otel_proto_rawDesc = "" +
	"\n" +
	"\x1eprivate_location/v1/otel.proto\x12\x13private_location.v1\"1\n" +
	"\aHeaders\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"`\n" +
	"\n" +
	"OtelConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x126\n" +
	"\aheaders\x18\x02 \x03(\v2\x1c.private_location.v1.HeadersR\aheadersBJZHgithub.com/openstatushq/openstatus/packages/proto/private_location/v1;v1b\x06proto3"

var (
	file_private_location_v1_otel_proto_rawDescOnce sync.Once
	file_private_location_v1_otel_proto_rawDescData []byte
)

func file_private_location_v1_otel_proto_rawDescGZIP() []byte {
	file_private_location_v1_otel_proto_rawDescOnce.Do(func() {
		file_private_location_v1_otel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_private_location_v1_otel_proto_rawDesc), len(file_private_location_v1_otel_proto_rawDesc)))
	})
	return file_private_location_v1_otel_proto_rawDescData
}

var file_private_location_v1_otel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_private_location_v1_otel_proto_goTypes = []any{
	(*Headers)(nil),    // 0: private_location.v1.Headers
	(*OtelConfig)(nil), // 1: private_location.v1.OtelConfig
}
var file_private_location_v1_otel_proto_depIdxs = []int32{
	0, // 0: private_location.v1.OtelConfig.headers:type_name -> private_location.v1.Headers
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_private_location_v1_otel_proto_init() }
func file_private_location_v1_otel_proto_init() {
	if File_private_location_v1_otel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_private_location_v1_otel_proto_rawDesc), len(file_private_location_v1_otel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_private_location_v1_otel_proto_goTypes,
		DependencyIndexes: file_private_location_v1_otel_proto_depIdxs,
		MessageInfos:      file_private_location_v1_otel_proto_msgTypes,
	}.Build()
	File_private_location_v1_otel_proto = out.File
	file_private_location_v1_otel_proto_goTypes = nil
	file_private_location_v1_otel_proto_depIdxs = nil
}
