import type { WorkspacePlan } from "../workspaces/validation";
import type { Limits } from "./schema";

// TODO: rename to `planConfig`
export const allPlans: Record<
  WorkspacePlan,
  {
    title: "Hobby" | "Starter" | "Pro";
    id: WorkspacePlan;
    description: string;
    price: number;
    limits: Limits;
  }
> = {
  free: {
    title: "Hobby",
    id: "free",
    description: "Perfect for personal projects",
    price: 0,
    limits: {
      monitors: 1,
      "synthetic-checks": 30,
      periodicity: ["10m", "30m", "1h"],
      "multi-region": true,
      "max-regions": 6,
      "data-retention": "14 days",
      "status-pages": 1,
      maintenance: true,
      "monitor-values-visibility": true,
      screenshots: false,
      otel: false,
      "status-subscribers": false,
      "custom-domain": false,
      "password-protection": false,
      "white-label": false,
      notifications: true,
      sms: false,
      pagerduty: false,
      opsgenie: false,
      "notification-channels": 1,
      members: 1,
      "audit-log": false,
      regions: ["ams", "gru", "iad", "jnb", "hkg", "syd"],
      "private-locations": false,
    },
  },
  starter: {
    title: "Starter",
    id: "starter",
    description: "Perfect for uptime monitoring",
    price: 30,
    limits: {
      monitors: 10,
      "synthetic-checks": 100,
      periodicity: ["1m", "5m", "10m", "30m", "1h"],
      "multi-region": true,
      "max-regions": 6,
      "data-retention": "3 months",
      "status-pages": 1,
      maintenance: true,
      "monitor-values-visibility": true,
      screenshots: true,
      otel: false,
      "status-subscribers": true,
      "custom-domain": true,
      "password-protection": true,
      "white-label": false,
      notifications: true,
      pagerduty: true,
      opsgenie: true,
      sms: true,
      "notification-channels": 10,
      members: "Unlimited",
      "audit-log": false,
      regions: [
        "ams",
        "arn",
        "atl",
        "bog",
        "bom",
        "bos",
        "cdg",
        "den",
        "dfw",
        "ewr",
        "eze",
        "fra",
        "gdl",
        "gig",
        "gru",
        "hkg",
        "iad",
        "jnb",
        "lax",
        "lhr",
        "mad",
        "mia",
        "nrt",
        "ord",
        "otp",
        "phx",
        "qro",
        "scl",
        "sea",
        "sin",
        "sjc",
        "syd",
        "waw",
        "yul",
        "yyz",
      ],
      "private-locations": false,
    },
  },
  team: {
    title: "Pro",
    id: "team",
    description: "Perfect for global synthetic monitoring",
    price: 100,
    limits: {
      monitors: 100,
      "synthetic-checks": 300,
      periodicity: ["30s", "1m", "5m", "10m", "30m", "1h"],
      "multi-region": true,
      "max-regions": 35,
      "data-retention": "12 months",
      "status-pages": 5,
      maintenance: true,
      "monitor-values-visibility": true,
      screenshots: true,
      otel: true,
      "status-subscribers": true,
      "custom-domain": true,
      "password-protection": true,
      "white-label": false,
      notifications: true,
      sms: true,
      pagerduty: true,
      opsgenie: true,
      "notification-channels": 20,
      members: "Unlimited",
      "audit-log": true,
      regions: [
        "ams",
        "arn",
        "atl",
        "bog",
        "bom",
        "bos",
        "cdg",
        "den",
        "dfw",
        "ewr",
        "eze",
        "fra",
        "gdl",
        "gig",
        "gru",
        "hkg",
        "iad",
        "jnb",
        "lax",
        "lhr",
        "mad",
        "mia",
        "nrt",
        "ord",
        "otp",
        "phx",
        "qro",
        "scl",
        "sea",
        "sin",
        "sjc",
        "syd",
        "waw",
        "yul",
        "yyz",
      ],
      "private-locations": false,
    },
  },
};
