export const statusCodes = [
  { value: 100, label: "Continue" },
  { value: 101, label: "Switching Protocols" },
  { value: 200, label: "OK" },
  { value: 201, label: "Created" },
  { value: 202, label: "Accepted" },
  { value: 203, label: "Non-Authoritative Information" },
  { value: 204, label: "No Content" },
  { value: 205, label: "Reset Content" },
  { value: 206, label: "Partial Content" },
  { value: 300, label: "Multiple Choices" },
  { value: 301, label: "Moved Permanently" },
  { value: 302, label: "Found" },
  { value: 303, label: "See Other" },
  { value: 304, label: "Not Modified" },
  { value: 307, label: "Temporary Redirect" },
  { value: 308, label: "Permanent Redirect" },
  { value: 400, label: "Bad Request" },
  { value: 401, label: "Unauthorized" },
  { value: 403, label: "Forbidden" },
  { value: 404, label: "Not Found" },
  { value: 405, label: "Method Not Allowed" },
  { value: 406, label: "Not Acceptable" },
  { value: 407, label: "Proxy Authentication Required" },
  { value: 408, label: "Request Timeout" },
  { value: 409, label: "Conflict" },
  { value: 410, label: "Gone" },
  { value: 411, label: "Length Required" },
  { value: 412, label: "Precondition Failed" },
  { value: 413, label: "Payload Too Large" },
  { value: 414, label: "URI Too Long" },
  { value: 415, label: "Unsupported Media Type" },
  { value: 416, label: "Range Not Satisfiable" },
  { value: 417, label: "Expectation Failed" },
  { value: 418, label: "I'm a teapot" },
  { value: 421, label: "Misdirected Request" },
  { value: 422, label: "Unprocessable Entity" },
  { value: 423, label: "Locked" },
  { value: 424, label: "Failed Dependency" },
  { value: 425, label: "Too Early" },
  { value: 426, label: "Upgrade Required" },
  { value: 428, label: "Precondition Required" },
  { value: 429, label: "Too Many Requests" },
  { value: 431, label: "Request Header Fields Too Large" },
  { value: 451, label: "Unavailable For Legal Reasons" },
  { value: 500, label: "Internal Server Error" },
  { value: 501, label: "Not Implemented" },
  { value: 502, label: "Bad Gateway" },
  { value: 503, label: "Service Unavailable" },
  { value: 504, label: "Gateway Timeout" },
  { value: 505, label: "HTTP Version Not Supported" },
  { value: 506, label: "Variant Also Negotiates" },
  { value: 507, label: "Insufficient Storage" },
  { value: 508, label: "Loop Detected" },
  { value: 510, label: "Not Extended" },
  { value: 511, label: "Network Authentication Required" },
];
