import type { Theme } from "./types";

export const DRACULA_THEME = {
  id: "dracula",
  name: "Dracula",
  author: { name: "@thibaultleouay", url: "https://thibaultleouay.dev" },
  light: {
    "--background": "#FFFBEB",
    "--foreground": "#1F1F1F",
    "--border": "#6C664B",
    "--input": "oklch(92.2% 0 0)",
    "--primary": "oklch(20.5% 0 0)",
    "--primary-foreground": "oklch(98.5% 0 0)",
    "--secondary": "oklch(97% 0 0)",
    "--secondary-foreground": "oklch(20.5% 0 0)",
    "--muted": "oklch(97% 0 0)",
    "--muted-foreground": "oklch(55.6% 0 0)",
    "--accent": "oklch(97% 0 0)",
    "--accent-foreground": "oklch(20.5% 0 0)",
    "--success": "#14710a",
    "--destructive": "#cb3a2a",
    "--warning": "#A34D14",
    "--info": "#036A96",
    "--popover-foreground": "var(--foreground)",
    "--popover": "var(--background)"
  },
  dark: {
    "--background": "#282a36",
    "--foreground": "#f8f8f2",
    "--border": "#6272A4",
    "--input": "oklch(100% 0 0 / 15%)",
    "--primary": "oklch(92.2% 0 0)",
    "--primary-foreground": "oklch(20.5% 0 0)",
    "--secondary": "oklch(26.9% 0 0)",
    "--secondary-foreground": "oklch(98.5% 0 0)",
    "--muted": "oklch(26.9% 0 0)",
    "--muted-foreground": "oklch(70.8% 0 0)",
    "--accent": "oklch(26.9% 0 0)",
    "--accent-foreground": "oklch(98.5% 0 0)",
    "--success": "#50fa7b",
    "--destructive": "#ff5555",
    "--warning": "#ffb86c",
    "--info": "#8BE9FD",
    "--popover-foreground": "var(--foreground)",
    "--popover": "var(--background)"
  },
} as const satisfies Theme;
