// Single import surface for icons across all openstatus apps.
// The nucleo set mirrors these names; see ../nucleo/index.ts.
export type { IconProps, IconType } from "../types";
export {
  Sparkles as AI,
  User as Account,
  Bookmark as Acknowledge,
  Plus as Add,
  Bot as Agent,
  CircleAlert as Alert,
  Braces as Api,
  Key as ApiKey,
  Workflow as ApiTrigger,
  ArrowDown,
  ArrowUpRight,
  AudioLines,
  ScanEye as AuditLog,
  ArrowLeft as Back,
  CreditCard as Billing,
  Newspaper as Blog,
  BookOpen,
  Calendar,
  ScrollText as Changelog,
  MessageCircle as Chat,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Clock,
  X as Close,
  Code,
  ChevronsDownUp as Collapse,
  Command,
  ArrowLeftRight as Compare,
  LayoutTemplate as Components,
  Copy,
  Moon as Dark,
  Database,
  Trash2 as Delete,
  Book as Docs,
  FileDown as Download,
  GripVertical as DragHandle,
  CopyPlus as Duplicate,
  Pencil as Edit,
  Mail as Email,
  CornerDownLeft as Enter,
  CircleX as Error,
  ChevronsUpDown as Expand,
  ExternalLink,
  CircleMinus as Failed,
  FileJson,
  FileText,
  Filter,
  Fingerprint,
  Globe,
  HelpCircle as Help,
  EyeOff as Hide,
  Image,
  Gauge as Impact,
  Inbox,
  Siren as Incident,
  Info,
  Blocks as Integrations,
  UserPlus as Invite,
  Rocket as Launch,
  Sun as Light,
  Link,
  Link2 as Linked,
  ListFilter,
  LoaderCircle as Loading,
  Lock,
  LogIn as Login,
  LogOut as Logout,
  Logs,
  Hammer as Maintenance,
  Menu,
  Mic,
  Activity as Monitor,
  MoreHorizontal as More,
  Network,
  ArrowRight as Next,
  Bell as Notification,
  LayoutGrid as Overview,
  CircleDashed as Pending,
  Play,
  Plug,
  ServerCog as PrivateLocation,
  RefreshCw as Refresh,
  MapPin as Region,
  Minus as Remove,
  Megaphone as Report,
  RotateCcw as Reset,
  SearchCheck as Resolved,
  ShieldAlert as Restricted,
  CalendarClock as Schedule,
  Search,
  Send,
  Server,
  Cog as Settings,
  Shield,
  ShieldUser,
  Eye as Show,
  PanelRight as Sidebar,
  PanelLeft as SidebarLeft,
  Zap as Speed,
  PanelTop as StatusPage,
  Square as Stop,
  CircleCheck as Success,
  LifeBuoy as Support,
  Laptop as System,
  Table,
  TableProperties,
  Tag,
  Users as Team,
  Terminal,
  Palette as Theme,
  TrendingUp as Trend,
  Link2Off as Unlinked,
  LockOpen as Unlock,
  TriangleAlert as Warning,
  Webhook,
} from "lucide-react";
