import {
  Activity,
  ArrowLeftRight,
  Clock,
  Cog,
  Command,
  Copy,
  Fingerprint,
  Globe,
  Hammer,
  Image,
  Info,
  Key,
  Link,
  Network,
  Play,
  Search,
  SearchCheck,
  Server,
  Table,
  User,
  Webhook,
  Zap,
} from "@openstatus/icons";
import type { LucideIcon, LucideProps } from "@openstatus/icons";
import {
  BlueskyIcon,
  DiscordIcon,
  GitHubIcon,
  LinkedInIcon,
  XIcon,
} from "@openstatus/icons/brand";

export type Icon = LucideIcon;
export type IconProps = LucideProps;
export type ValidIcon = keyof typeof Icons;

export const Icons = {
  activity: Activity,
  clock: Clock,
  cog: Cog,
  command: Command,
  compare: ArrowLeftRight,
  copy: Copy,
  fingerprint: Fingerprint,
  globe: Globe,
  hammer: Hammer,
  image: Image,
  info: Info,
  key: Key,
  link: Link,
  network: Network,
  play: Play,
  search: Search,
  "search-check": SearchCheck,
  server: Server,
  table: Table,
  user: User,
  webhook: Webhook,
  zap: Zap,
  bluesky: BlueskyIcon,
  discord: DiscordIcon,
  github: GitHubIcon,
  linkedin: LinkedInIcon,
  twitter: XIcon,
} as const;
