import {
  Monitor,
  Compare,
  Clock,
  Settings,
  Command,
  Copy,
  Fingerprint,
  Globe,
  Maintenance,
  Image,
  Info,
  ApiKey,
  Link,
  Network,
  Play,
  Search,
  Resolved,
  Server,
  Table,
  Account,
  Webhook,
  Speed,
} from "@openstatus/icons";
import type { IconType, IconProps } from "@openstatus/icons";
import {
  BlueskyIcon,
  DiscordIcon,
  GitHubIcon,
  LinkedInIcon,
  XIcon,
} from "@openstatus/icons/brand";

export type Icon = IconType;
export type { IconProps };
export type ValidIcon = keyof typeof Icons;

export const Icons = {
  activity: Monitor,
  clock: Clock,
  cog: Settings,
  command: Command,
  compare: Compare,
  copy: Copy,
  fingerprint: Fingerprint,
  globe: Globe,
  hammer: Maintenance,
  image: Image,
  info: Info,
  key: ApiKey,
  link: Link,
  network: Network,
  play: Play,
  search: Search,
  "search-check": Resolved,
  server: Server,
  table: Table,
  user: Account,
  webhook: Webhook,
  zap: Speed,
  bluesky: BlueskyIcon,
  discord: DiscordIcon,
  github: GitHubIcon,
  linkedin: LinkedInIcon,
  twitter: XIcon,
} as const;
