// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: private_location/v1/grpc_monitor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GRPCMonitor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uri           string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	Timeout       int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	DegradedAt    *int64                 `protobuf:"varint,4,opt,name=degraded_at,json=degradedAt,proto3,oneof" json:"degraded_at,omitempty"`
	Periodicity   string                 `protobuf:"bytes,5,opt,name=periodicity,proto3" json:"periodicity,omitempty"`
	Retry         int64                  `protobuf:"varint,6,opt,name=retry,proto3" json:"retry,omitempty"`
	Service       string                 `protobuf:"bytes,7,opt,name=service,proto3" json:"service,omitempty"`
	TlsMode       string                 `protobuf:"bytes,8,opt,name=tls_mode,json=tlsMode,proto3" json:"tls_mode,omitempty"`
	Metadata      []*Headers             `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty"`
	OtelConfig    *OtelConfig            `protobuf:"bytes,20,opt,name=otel_config,json=otelConfig,proto3" json:"otel_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCMonitor) Reset() {
	*x = GRPCMonitor{}
	mi := &file_private_location_v1_grpc_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCMonitor) ProtoMessage() {}

func (x *GRPCMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_grpc_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCMonitor.ProtoReflect.Descriptor instead.
func (*GRPCMonitor) Descriptor() ([]byte, []int) {
	return file_private_location_v1_grpc_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *GRPCMonitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GRPCMonitor) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *GRPCMonitor) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *GRPCMonitor) GetDegradedAt() int64 {
	if x != nil && x.DegradedAt != nil {
		return *x.DegradedAt
	}
	return 0
}

func (x *GRPCMonitor) GetPeriodicity() string {
	if x != nil {
		return x.Periodicity
	}
	return ""
}

func (x *GRPCMonitor) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *GRPCMonitor) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GRPCMonitor) GetTlsMode() string {
	if x != nil {
		return x.TlsMode
	}
	return ""
}

func (x *GRPCMonitor) GetMetadata() []*Headers {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GRPCMonitor) GetOtelConfig() *OtelConfig {
	if x != nil {
		return x.OtelConfig
	}
	return nil
}

var File_private_location_v1_grpc_monitor_proto protoreflect.FileDescriptor

const file_private_location_v1_grpc_monitor_proto_rawDesc = "" +
	"\n" +
	"&private_location/v1/grpc_monitor.proto\x12\x13private_location.v1\x1a\x1eprivate_location/v1/otel.proto\"\xe8\x02\n" +
	"\vGRPCMonitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\x12$\n" +
	"\vdegraded_at\x18\x04 \x01(\x03H\x00R\n" +
	"degradedAt\x88\x01\x01\x12 \n" +
	"\vperiodicity\x18\x05 \x01(\tR\vperiodicity\x12\x14\n" +
	"\x05retry\x18\x06 \x01(\x03R\x05retry\x12\x18\n" +
	"\aservice\x18\a \x01(\tR\aservice\x12\x19\n" +
	"\btls_mode\x18\b \x01(\tR\atlsMode\x128\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x1c.private_location.v1.HeadersR\bmetadata\x12@\n" +
	"\votel_config\x18\x14 \x01(\v2\x1f.private_location.v1.OtelConfigR\n" +
	"otelConfigB\x0e\n" +
	"\f_degraded_atBJZHgithub.com/openstatushq/openstatus/packages/proto/private_location/v1;v1b\x06proto3"

var (
	file_private_location_v1_grpc_monitor_proto_rawDescOnce sync.Once
	file_private_location_v1_grpc_monitor_proto_rawDescData []byte
)

func file_private_location_v1_grpc_monitor_proto_rawDescGZIP() []byte {
	file_private_location_v1_grpc_monitor_proto_rawDescOnce.Do(func() {
		file_private_location_v1_grpc_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_private_location_v1_grpc_monitor_proto_rawDesc), len(file_private_location_v1_grpc_monitor_proto_rawDesc)))
	})
	return file_private_location_v1_grpc_monitor_proto_rawDescData
}

var file_private_location_v1_grpc_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_private_location_v1_grpc_monitor_proto_goTypes = []any{
	(*GRPCMonitor)(nil), // 0: private_location.v1.GRPCMonitor
	(*Headers)(nil),     // 1: private_location.v1.Headers
	(*OtelConfig)(nil),  // 2: private_location.v1.OtelConfig
}
var file_private_location_v1_grpc_monitor_proto_depIdxs = []int32{
	1, // 0: private_location.v1.GRPCMonitor.metadata:type_name -> private_location.v1.Headers
	2, // 1: private_location.v1.GRPCMonitor.otel_config:type_name -> private_location.v1.OtelConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_private_location_v1_grpc_monitor_proto_init() }
func file_private_location_v1_grpc_monitor_proto_init() {
	if File_private_location_v1_grpc_monitor_proto != nil {
		return
	}
	file_private_location_v1_otel_proto_init()
	file_private_location_v1_grpc_monitor_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_private_location_v1_grpc_monitor_proto_rawDesc), len(file_private_location_v1_grpc_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_private_location_v1_grpc_monitor_proto_goTypes,
		DependencyIndexes: file_private_location_v1_grpc_monitor_proto_depIdxs,
		MessageInfos:      file_private_location_v1_grpc_monitor_proto_msgTypes,
	}.Build()
	File_private_location_v1_grpc_monitor_proto = out.File
	file_private_location_v1_grpc_monitor_proto_goTypes = nil
	file_private_location_v1_grpc_monitor_proto_depIdxs = nil
}
