// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: private_location/v1/http_monitor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Headers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Headers) Reset() {
	*x = Headers{}
	mi := &file_private_location_v1_http_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Headers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Headers) ProtoMessage() {}

func (x *Headers) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_http_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Headers.ProtoReflect.Descriptor instead.
func (*Headers) Descriptor() ([]byte, []int) {
	return file_private_location_v1_http_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *Headers) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Headers) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HTTPMonitor struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Periodicity          string                 `protobuf:"bytes,3,opt,name=periodicity,proto3" json:"periodicity,omitempty"`
	Method               string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Body                 string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Timeout              int64                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	DegradedAt           *int64                 `protobuf:"varint,7,opt,name=degraded_at,json=degradedAt,proto3,oneof" json:"degraded_at,omitempty"`
	Retry                int64                  `protobuf:"varint,8,opt,name=retry,proto3" json:"retry,omitempty"`
	FollowRedirects      bool                   `protobuf:"varint,9,opt,name=follow_redirects,json=followRedirects,proto3" json:"follow_redirects,omitempty"`
	Headers              []*Headers             `protobuf:"bytes,10,rep,name=headers,proto3" json:"headers,omitempty"`
	StatusCodeAssertions []*StatusCodeAssertion `protobuf:"bytes,11,rep,name=status_code_assertions,json=statusCodeAssertions,proto3" json:"status_code_assertions,omitempty"`
	BodyAssertions       []*BodyAssertion       `protobuf:"bytes,12,rep,name=body_assertions,json=bodyAssertions,proto3" json:"body_assertions,omitempty"`
	HeaderAssertions     []*HeaderAssertion     `protobuf:"bytes,13,rep,name=header_assertions,json=headerAssertions,proto3" json:"header_assertions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HTTPMonitor) Reset() {
	*x = HTTPMonitor{}
	mi := &file_private_location_v1_http_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPMonitor) ProtoMessage() {}

func (x *HTTPMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_http_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPMonitor.ProtoReflect.Descriptor instead.
func (*HTTPMonitor) Descriptor() ([]byte, []int) {
	return file_private_location_v1_http_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *HTTPMonitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HTTPMonitor) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPMonitor) GetPeriodicity() string {
	if x != nil {
		return x.Periodicity
	}
	return ""
}

func (x *HTTPMonitor) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPMonitor) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *HTTPMonitor) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *HTTPMonitor) GetDegradedAt() int64 {
	if x != nil && x.DegradedAt != nil {
		return *x.DegradedAt
	}
	return 0
}

func (x *HTTPMonitor) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *HTTPMonitor) GetFollowRedirects() bool {
	if x != nil {
		return x.FollowRedirects
	}
	return false
}

func (x *HTTPMonitor) GetHeaders() []*Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPMonitor) GetStatusCodeAssertions() []*StatusCodeAssertion {
	if x != nil {
		return x.StatusCodeAssertions
	}
	return nil
}

func (x *HTTPMonitor) GetBodyAssertions() []*BodyAssertion {
	if x != nil {
		return x.BodyAssertions
	}
	return nil
}

func (x *HTTPMonitor) GetHeaderAssertions() []*HeaderAssertion {
	if x != nil {
		return x.HeaderAssertions
	}
	return nil
}

var File_private_location_v1_http_monitor_proto protoreflect.FileDescriptor

const file_private_location_v1_http_monitor_proto_rawDesc = "" +
	"\n" +
	"&private_location/v1/http_monitor.proto\x12\x13private_location.v1\x1a$private_location/v1/assertions.proto\"1\n" +
	"\aHeaders\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc6\x04\n" +
	"\vHTTPMonitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12 \n" +
	"\vperiodicity\x18\x03 \x01(\tR\vperiodicity\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x03R\atimeout\x12$\n" +
	"\vdegraded_at\x18\a \x01(\x03H\x00R\n" +
	"degradedAt\x88\x01\x01\x12\x14\n" +
	"\x05retry\x18\b \x01(\x03R\x05retry\x12)\n" +
	"\x10follow_redirects\x18\t \x01(\bR\x0ffollowRedirects\x126\n" +
	"\aheaders\x18\n" +
	" \x03(\v2\x1c.private_location.v1.HeadersR\aheaders\x12^\n" +
	"\x16status_code_assertions\x18\v \x03(\v2(.private_location.v1.StatusCodeAssertionR\x14statusCodeAssertions\x12K\n" +
	"\x0fbody_assertions\x18\f \x03(\v2\".private_location.v1.BodyAssertionR\x0ebodyAssertions\x12Q\n" +
	"\x11header_assertions\x18\r \x03(\v2$.private_location.v1.HeaderAssertionR\x10headerAssertionsB\x0e\n" +
	"\f_degraded_atBJZHgithub.com/openstatushq/openstatus/packages/proto/private_location/v1;v1b\x06proto3"

var (
	file_private_location_v1_http_monitor_proto_rawDescOnce sync.Once
	file_private_location_v1_http_monitor_proto_rawDescData []byte
)

func file_private_location_v1_http_monitor_proto_rawDescGZIP() []byte {
	file_private_location_v1_http_monitor_proto_rawDescOnce.Do(func() {
		file_private_location_v1_http_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_private_location_v1_http_monitor_proto_rawDesc), len(file_private_location_v1_http_monitor_proto_rawDesc)))
	})
	return file_private_location_v1_http_monitor_proto_rawDescData
}

var file_private_location_v1_http_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_private_location_v1_http_monitor_proto_goTypes = []any{
	(*Headers)(nil),             // 0: private_location.v1.Headers
	(*HTTPMonitor)(nil),         // 1: private_location.v1.HTTPMonitor
	(*StatusCodeAssertion)(nil), // 2: private_location.v1.StatusCodeAssertion
	(*BodyAssertion)(nil),       // 3: private_location.v1.BodyAssertion
	(*HeaderAssertion)(nil),     // 4: private_location.v1.HeaderAssertion
}
var file_private_location_v1_http_monitor_proto_depIdxs = []int32{
	0, // 0: private_location.v1.HTTPMonitor.headers:type_name -> private_location.v1.Headers
	2, // 1: private_location.v1.HTTPMonitor.status_code_assertions:type_name -> private_location.v1.StatusCodeAssertion
	3, // 2: private_location.v1.HTTPMonitor.body_assertions:type_name -> private_location.v1.BodyAssertion
	4, // 3: private_location.v1.HTTPMonitor.header_assertions:type_name -> private_location.v1.HeaderAssertion
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_private_location_v1_http_monitor_proto_init() }
func file_private_location_v1_http_monitor_proto_init() {
	if File_private_location_v1_http_monitor_proto != nil {
		return
	}
	file_private_location_v1_assertions_proto_init()
	file_private_location_v1_http_monitor_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_private_location_v1_http_monitor_proto_rawDesc), len(file_private_location_v1_http_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_private_location_v1_http_monitor_proto_goTypes,
		DependencyIndexes: file_private_location_v1_http_monitor_proto_depIdxs,
		MessageInfos:      file_private_location_v1_http_monitor_proto_msgTypes,
	}.Build()
	File_private_location_v1_http_monitor_proto = out.File
	file_private_location_v1_http_monitor_proto_goTypes = nil
	file_private_location_v1_http_monitor_proto_depIdxs = nil
}
