// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: private_location/v1/private_location.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumberComparator int32

const (
	NumberComparator_NUMBER_COMPARATOR_UNSPECIFIED           NumberComparator = 0
	NumberComparator_NUMBER_COMPARATOR_EQUAL                 NumberComparator = 1
	NumberComparator_NUMBER_COMPARATOR_NOT_EQUAL             NumberComparator = 2
	NumberComparator_NUMBER_COMPARATOR_GREATER_THAN          NumberComparator = 3
	NumberComparator_NUMBER_COMPARATOR_GREATER_THAN_OR_EQUAL NumberComparator = 4
	NumberComparator_NUMBER_COMPARATOR_LESS_THAN             NumberComparator = 5
	NumberComparator_NUMBER_COMPARATOR_LESS_THAN_OR_EQUAL    NumberComparator = 6
)

// Enum value maps for NumberComparator.
var (
	NumberComparator_name = map[int32]string{
		0: "NUMBER_COMPARATOR_UNSPECIFIED",
		1: "NUMBER_COMPARATOR_EQUAL",
		2: "NUMBER_COMPARATOR_NOT_EQUAL",
		3: "NUMBER_COMPARATOR_GREATER_THAN",
		4: "NUMBER_COMPARATOR_GREATER_THAN_OR_EQUAL",
		5: "NUMBER_COMPARATOR_LESS_THAN",
		6: "NUMBER_COMPARATOR_LESS_THAN_OR_EQUAL",
	}
	NumberComparator_value = map[string]int32{
		"NUMBER_COMPARATOR_UNSPECIFIED":           0,
		"NUMBER_COMPARATOR_EQUAL":                 1,
		"NUMBER_COMPARATOR_NOT_EQUAL":             2,
		"NUMBER_COMPARATOR_GREATER_THAN":          3,
		"NUMBER_COMPARATOR_GREATER_THAN_OR_EQUAL": 4,
		"NUMBER_COMPARATOR_LESS_THAN":             5,
		"NUMBER_COMPARATOR_LESS_THAN_OR_EQUAL":    6,
	}
)

func (x NumberComparator) Enum() *NumberComparator {
	p := new(NumberComparator)
	*p = x
	return p
}

func (x NumberComparator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumberComparator) Descriptor() protoreflect.EnumDescriptor {
	return file_private_location_v1_private_location_proto_enumTypes[0].Descriptor()
}

func (NumberComparator) Type() protoreflect.EnumType {
	return &file_private_location_v1_private_location_proto_enumTypes[0]
}

func (x NumberComparator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumberComparator.Descriptor instead.
func (NumberComparator) EnumDescriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{0}
}

type StringComparator int32

const (
	StringComparator_STRING_COMPARATOR_UNSPECIFIED           StringComparator = 0
	StringComparator_STRING_COMPARATOR_CONTAINS              StringComparator = 1
	StringComparator_STRING_COMPARATOR_NOT_CONTAINS          StringComparator = 2
	StringComparator_STRING_COMPARATOR_EQUAL                 StringComparator = 3
	StringComparator_STRING_COMPARATOR_NOT_EQUAL             StringComparator = 4
	StringComparator_STRING_COMPARATOR_EMPTY                 StringComparator = 5
	StringComparator_STRING_COMPARATOR_NOT_EMPTY             StringComparator = 6
	StringComparator_STRING_COMPARATOR_GREATER_THAN          StringComparator = 7
	StringComparator_STRING_COMPARATOR_GREATER_THAN_OR_EQUAL StringComparator = 8
	StringComparator_STRING_COMPARATOR_LESS_THAN             StringComparator = 9
	StringComparator_STRING_COMPARATOR_LESS_THAN_OR_EQUAL    StringComparator = 10
)

// Enum value maps for StringComparator.
var (
	StringComparator_name = map[int32]string{
		0:  "STRING_COMPARATOR_UNSPECIFIED",
		1:  "STRING_COMPARATOR_CONTAINS",
		2:  "STRING_COMPARATOR_NOT_CONTAINS",
		3:  "STRING_COMPARATOR_EQUAL",
		4:  "STRING_COMPARATOR_NOT_EQUAL",
		5:  "STRING_COMPARATOR_EMPTY",
		6:  "STRING_COMPARATOR_NOT_EMPTY",
		7:  "STRING_COMPARATOR_GREATER_THAN",
		8:  "STRING_COMPARATOR_GREATER_THAN_OR_EQUAL",
		9:  "STRING_COMPARATOR_LESS_THAN",
		10: "STRING_COMPARATOR_LESS_THAN_OR_EQUAL",
	}
	StringComparator_value = map[string]int32{
		"STRING_COMPARATOR_UNSPECIFIED":           0,
		"STRING_COMPARATOR_CONTAINS":              1,
		"STRING_COMPARATOR_NOT_CONTAINS":          2,
		"STRING_COMPARATOR_EQUAL":                 3,
		"STRING_COMPARATOR_NOT_EQUAL":             4,
		"STRING_COMPARATOR_EMPTY":                 5,
		"STRING_COMPARATOR_NOT_EMPTY":             6,
		"STRING_COMPARATOR_GREATER_THAN":          7,
		"STRING_COMPARATOR_GREATER_THAN_OR_EQUAL": 8,
		"STRING_COMPARATOR_LESS_THAN":             9,
		"STRING_COMPARATOR_LESS_THAN_OR_EQUAL":    10,
	}
)

func (x StringComparator) Enum() *StringComparator {
	p := new(StringComparator)
	*p = x
	return p
}

func (x StringComparator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StringComparator) Descriptor() protoreflect.EnumDescriptor {
	return file_private_location_v1_private_location_proto_enumTypes[1].Descriptor()
}

func (StringComparator) Type() protoreflect.EnumType {
	return &file_private_location_v1_private_location_proto_enumTypes[1]
}

func (x StringComparator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StringComparator.Descriptor instead.
func (StringComparator) EnumDescriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{1}
}

type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	JobType_JOB_TYPE_HTTP        JobType = 1
	JobType_JOB_TYPE_TCP         JobType = 2
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_HTTP",
		2: "JOB_TYPE_TCP",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_HTTP":        1,
		"JOB_TYPE_TCP":         2,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_private_location_v1_private_location_proto_enumTypes[2].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_private_location_v1_private_location_proto_enumTypes[2]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{2}
}

type MonitorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorsRequest) Reset() {
	*x = MonitorsRequest{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorsRequest) ProtoMessage() {}

func (x *MonitorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorsRequest.ProtoReflect.Descriptor instead.
func (*MonitorsRequest) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{0}
}

type MonitorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitors      []*HTTPMonitor         `protobuf:"bytes,1,rep,name=monitors,proto3" json:"monitors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorsResponse) Reset() {
	*x = MonitorsResponse{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorsResponse) ProtoMessage() {}

func (x *MonitorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorsResponse.ProtoReflect.Descriptor instead.
func (*MonitorsResponse) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorsResponse) GetMonitors() []*HTTPMonitor {
	if x != nil {
		return x.Monitors
	}
	return nil
}

type Monitors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monitors      []*Monitor             `protobuf:"bytes,1,rep,name=monitors,proto3" json:"monitors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monitors) Reset() {
	*x = Monitors{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monitors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monitors) ProtoMessage() {}

func (x *Monitors) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monitors.ProtoReflect.Descriptor instead.
func (*Monitors) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{2}
}

func (x *Monitors) GetMonitors() []*Monitor {
	if x != nil {
		return x.Monitors
	}
	return nil
}

type Monitor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpMonitor   []*HTTPMonitor         `protobuf:"bytes,1,rep,name=http_monitor,json=httpMonitor,proto3" json:"http_monitor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Monitor) Reset() {
	*x = Monitor{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Monitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monitor) ProtoMessage() {}

func (x *Monitor) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monitor.ProtoReflect.Descriptor instead.
func (*Monitor) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{3}
}

func (x *Monitor) GetHttpMonitor() []*HTTPMonitor {
	if x != nil {
		return x.HttpMonitor
	}
	return nil
}

type StatusCodeAssertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        int64                  `protobuf:"varint,1,opt,name=target,proto3" json:"target,omitempty"`
	Comparator    NumberComparator       `protobuf:"varint,2,opt,name=comparator,proto3,enum=private_location.v1.NumberComparator" json:"comparator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCodeAssertion) Reset() {
	*x = StatusCodeAssertion{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCodeAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCodeAssertion) ProtoMessage() {}

func (x *StatusCodeAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCodeAssertion.ProtoReflect.Descriptor instead.
func (*StatusCodeAssertion) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{4}
}

func (x *StatusCodeAssertion) GetTarget() int64 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *StatusCodeAssertion) GetComparator() NumberComparator {
	if x != nil {
		return x.Comparator
	}
	return NumberComparator_NUMBER_COMPARATOR_UNSPECIFIED
}

type BodyAssertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Comparator    StringComparator       `protobuf:"varint,2,opt,name=comparator,proto3,enum=private_location.v1.StringComparator" json:"comparator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyAssertion) Reset() {
	*x = BodyAssertion{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyAssertion) ProtoMessage() {}

func (x *BodyAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyAssertion.ProtoReflect.Descriptor instead.
func (*BodyAssertion) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{5}
}

func (x *BodyAssertion) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *BodyAssertion) GetComparator() StringComparator {
	if x != nil {
		return x.Comparator
	}
	return StringComparator_STRING_COMPARATOR_UNSPECIFIED
}

type HeaderAssertion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Comparator    StringComparator       `protobuf:"varint,2,opt,name=comparator,proto3,enum=private_location.v1.StringComparator" json:"comparator,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderAssertion) Reset() {
	*x = HeaderAssertion{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderAssertion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderAssertion) ProtoMessage() {}

func (x *HeaderAssertion) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderAssertion.ProtoReflect.Descriptor instead.
func (*HeaderAssertion) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{6}
}

func (x *HeaderAssertion) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *HeaderAssertion) GetComparator() StringComparator {
	if x != nil {
		return x.Comparator
	}
	return StringComparator_STRING_COMPARATOR_UNSPECIFIED
}

func (x *HeaderAssertion) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type Headers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Headers) Reset() {
	*x = Headers{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Headers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Headers) ProtoMessage() {}

func (x *Headers) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Headers.ProtoReflect.Descriptor instead.
func (*Headers) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{7}
}

func (x *Headers) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Headers) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HTTPMonitor struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Method               string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Body                 string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Timeout              int64                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	DegradedAt           *int64                 `protobuf:"varint,6,opt,name=degraded_at,json=degradedAt,proto3,oneof" json:"degraded_at,omitempty"`
	Retry                int64                  `protobuf:"varint,7,opt,name=retry,proto3" json:"retry,omitempty"`
	FollowRedirects      bool                   `protobuf:"varint,8,opt,name=follow_redirects,json=followRedirects,proto3" json:"follow_redirects,omitempty"`
	Headers              []*Headers             `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers,omitempty"`
	StatusCodeAssertions []*StatusCodeAssertion `protobuf:"bytes,10,rep,name=status_code_assertions,json=statusCodeAssertions,proto3" json:"status_code_assertions,omitempty"`
	BodyAssertions       []*BodyAssertion       `protobuf:"bytes,11,rep,name=body_assertions,json=bodyAssertions,proto3" json:"body_assertions,omitempty"`
	HeaderAssertions     []*HeaderAssertion     `protobuf:"bytes,12,rep,name=header_assertions,json=headerAssertions,proto3" json:"header_assertions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HTTPMonitor) Reset() {
	*x = HTTPMonitor{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPMonitor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPMonitor) ProtoMessage() {}

func (x *HTTPMonitor) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPMonitor.ProtoReflect.Descriptor instead.
func (*HTTPMonitor) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{8}
}

func (x *HTTPMonitor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HTTPMonitor) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HTTPMonitor) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPMonitor) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *HTTPMonitor) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *HTTPMonitor) GetDegradedAt() int64 {
	if x != nil && x.DegradedAt != nil {
		return *x.DegradedAt
	}
	return 0
}

func (x *HTTPMonitor) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *HTTPMonitor) GetFollowRedirects() bool {
	if x != nil {
		return x.FollowRedirects
	}
	return false
}

func (x *HTTPMonitor) GetHeaders() []*Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPMonitor) GetStatusCodeAssertions() []*StatusCodeAssertion {
	if x != nil {
		return x.StatusCodeAssertions
	}
	return nil
}

func (x *HTTPMonitor) GetBodyAssertions() []*BodyAssertion {
	if x != nil {
		return x.BodyAssertions
	}
	return nil
}

func (x *HTTPMonitor) GetHeaderAssertions() []*HeaderAssertion {
	if x != nil {
		return x.HeaderAssertions
	}
	return nil
}

var File_private_location_v1_private_location_proto protoreflect.FileDescriptor

const file_private_location_v1_private_location_proto_rawDesc = "" +
	"\n" +
	"*private_location/v1/private_location.proto\x12\x13private_location.v1\"\x11\n" +
	"\x0fMonitorsRequest\"P\n" +
	"\x10MonitorsResponse\x12<\n" +
	"\bmonitors\x18\x01 \x03(\v2 .private_location.v1.HTTPMonitorR\bmonitors\"D\n" +
	"\bMonitors\x128\n" +
	"\bmonitors\x18\x01 \x03(\v2\x1c.private_location.v1.MonitorR\bmonitors\"N\n" +
	"\aMonitor\x12C\n" +
	"\fhttp_monitor\x18\x01 \x03(\v2 .private_location.v1.HTTPMonitorR\vhttpMonitor\"t\n" +
	"\x13StatusCodeAssertion\x12\x16\n" +
	"\x06target\x18\x01 \x01(\x03R\x06target\x12E\n" +
	"\n" +
	"comparator\x18\x02 \x01(\x0e2%.private_location.v1.NumberComparatorR\n" +
	"comparator\"n\n" +
	"\rBodyAssertion\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12E\n" +
	"\n" +
	"comparator\x18\x02 \x01(\x0e2%.private_location.v1.StringComparatorR\n" +
	"comparator\"\x82\x01\n" +
	"\x0fHeaderAssertion\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12E\n" +
	"\n" +
	"comparator\x18\x02 \x01(\x0e2%.private_location.v1.StringComparatorR\n" +
	"comparator\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\"1\n" +
	"\aHeaders\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa4\x04\n" +
	"\vHTTPMonitor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x03R\atimeout\x12$\n" +
	"\vdegraded_at\x18\x06 \x01(\x03H\x00R\n" +
	"degradedAt\x88\x01\x01\x12\x14\n" +
	"\x05retry\x18\a \x01(\x03R\x05retry\x12)\n" +
	"\x10follow_redirects\x18\b \x01(\bR\x0ffollowRedirects\x126\n" +
	"\aheaders\x18\t \x03(\v2\x1c.private_location.v1.HeadersR\aheaders\x12^\n" +
	"\x16status_code_assertions\x18\n" +
	" \x03(\v2(.private_location.v1.StatusCodeAssertionR\x14statusCodeAssertions\x12K\n" +
	"\x0fbody_assertions\x18\v \x03(\v2\".private_location.v1.BodyAssertionR\x0ebodyAssertions\x12Q\n" +
	"\x11header_assertions\x18\f \x03(\v2$.private_location.v1.HeaderAssertionR\x10headerAssertionsB\x0e\n" +
	"\f_degraded_at*\x8f\x02\n" +
	"\x10NumberComparator\x12!\n" +
	"\x1dNUMBER_COMPARATOR_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17NUMBER_COMPARATOR_EQUAL\x10\x01\x12\x1f\n" +
	"\x1bNUMBER_COMPARATOR_NOT_EQUAL\x10\x02\x12\"\n" +
	"\x1eNUMBER_COMPARATOR_GREATER_THAN\x10\x03\x12+\n" +
	"'NUMBER_COMPARATOR_GREATER_THAN_OR_EQUAL\x10\x04\x12\x1f\n" +
	"\x1bNUMBER_COMPARATOR_LESS_THAN\x10\x05\x12(\n" +
	"$NUMBER_COMPARATOR_LESS_THAN_OR_EQUAL\x10\x06*\x91\x03\n" +
	"\x10StringComparator\x12!\n" +
	"\x1dSTRING_COMPARATOR_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSTRING_COMPARATOR_CONTAINS\x10\x01\x12\"\n" +
	"\x1eSTRING_COMPARATOR_NOT_CONTAINS\x10\x02\x12\x1b\n" +
	"\x17STRING_COMPARATOR_EQUAL\x10\x03\x12\x1f\n" +
	"\x1bSTRING_COMPARATOR_NOT_EQUAL\x10\x04\x12\x1b\n" +
	"\x17STRING_COMPARATOR_EMPTY\x10\x05\x12\x1f\n" +
	"\x1bSTRING_COMPARATOR_NOT_EMPTY\x10\x06\x12\"\n" +
	"\x1eSTRING_COMPARATOR_GREATER_THAN\x10\a\x12+\n" +
	"'STRING_COMPARATOR_GREATER_THAN_OR_EQUAL\x10\b\x12\x1f\n" +
	"\x1bSTRING_COMPARATOR_LESS_THAN\x10\t\x12(\n" +
	"$STRING_COMPARATOR_LESS_THAN_OR_EQUAL\x10\n" +
	"*H\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rJOB_TYPE_HTTP\x10\x01\x12\x10\n" +
	"\fJOB_TYPE_TCP\x10\x022s\n" +
	"\x16PrivateLocationService\x12Y\n" +
	"\bMonitors\x12$.private_location.v1.MonitorsRequest\x1a%.private_location.v1.MonitorsResponse\"\x00b\x06proto3"

var (
	file_private_location_v1_private_location_proto_rawDescOnce sync.Once
	file_private_location_v1_private_location_proto_rawDescData []byte
)

func file_private_location_v1_private_location_proto_rawDescGZIP() []byte {
	file_private_location_v1_private_location_proto_rawDescOnce.Do(func() {
		file_private_location_v1_private_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_private_location_v1_private_location_proto_rawDesc), len(file_private_location_v1_private_location_proto_rawDesc)))
	})
	return file_private_location_v1_private_location_proto_rawDescData
}

var file_private_location_v1_private_location_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_private_location_v1_private_location_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_private_location_v1_private_location_proto_goTypes = []any{
	(NumberComparator)(0),       // 0: private_location.v1.NumberComparator
	(StringComparator)(0),       // 1: private_location.v1.StringComparator
	(JobType)(0),                // 2: private_location.v1.JobType
	(*MonitorsRequest)(nil),     // 3: private_location.v1.MonitorsRequest
	(*MonitorsResponse)(nil),    // 4: private_location.v1.MonitorsResponse
	(*Monitors)(nil),            // 5: private_location.v1.Monitors
	(*Monitor)(nil),             // 6: private_location.v1.Monitor
	(*StatusCodeAssertion)(nil), // 7: private_location.v1.StatusCodeAssertion
	(*BodyAssertion)(nil),       // 8: private_location.v1.BodyAssertion
	(*HeaderAssertion)(nil),     // 9: private_location.v1.HeaderAssertion
	(*Headers)(nil),             // 10: private_location.v1.Headers
	(*HTTPMonitor)(nil),         // 11: private_location.v1.HTTPMonitor
}
var file_private_location_v1_private_location_proto_depIdxs = []int32{
	11, // 0: private_location.v1.MonitorsResponse.monitors:type_name -> private_location.v1.HTTPMonitor
	6,  // 1: private_location.v1.Monitors.monitors:type_name -> private_location.v1.Monitor
	11, // 2: private_location.v1.Monitor.http_monitor:type_name -> private_location.v1.HTTPMonitor
	0,  // 3: private_location.v1.StatusCodeAssertion.comparator:type_name -> private_location.v1.NumberComparator
	1,  // 4: private_location.v1.BodyAssertion.comparator:type_name -> private_location.v1.StringComparator
	1,  // 5: private_location.v1.HeaderAssertion.comparator:type_name -> private_location.v1.StringComparator
	10, // 6: private_location.v1.HTTPMonitor.headers:type_name -> private_location.v1.Headers
	7,  // 7: private_location.v1.HTTPMonitor.status_code_assertions:type_name -> private_location.v1.StatusCodeAssertion
	8,  // 8: private_location.v1.HTTPMonitor.body_assertions:type_name -> private_location.v1.BodyAssertion
	9,  // 9: private_location.v1.HTTPMonitor.header_assertions:type_name -> private_location.v1.HeaderAssertion
	3,  // 10: private_location.v1.PrivateLocationService.Monitors:input_type -> private_location.v1.MonitorsRequest
	4,  // 11: private_location.v1.PrivateLocationService.Monitors:output_type -> private_location.v1.MonitorsResponse
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_private_location_v1_private_location_proto_init() }
func file_private_location_v1_private_location_proto_init() {
	if File_private_location_v1_private_location_proto != nil {
		return
	}
	file_private_location_v1_private_location_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_private_location_v1_private_location_proto_rawDesc), len(file_private_location_v1_private_location_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_private_location_v1_private_location_proto_goTypes,
		DependencyIndexes: file_private_location_v1_private_location_proto_depIdxs,
		EnumInfos:         file_private_location_v1_private_location_proto_enumTypes,
		MessageInfos:      file_private_location_v1_private_location_proto_msgTypes,
	}.Build()
	File_private_location_v1_private_location_proto = out.File
	file_private_location_v1_private_location_proto_goTypes = nil
	file_private_location_v1_private_location_proto_depIdxs = nil
}
