// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: private_location/v1/private_location.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobType int32

const (
	JobType_JOB_TYPE_UNSPECIFIED JobType = 0
	JobType_JOB_TYPE_HTTP        JobType = 1
	JobType_JOB_TYPE_TCP         JobType = 2
)

// Enum value maps for JobType.
var (
	JobType_name = map[int32]string{
		0: "JOB_TYPE_UNSPECIFIED",
		1: "JOB_TYPE_HTTP",
		2: "JOB_TYPE_TCP",
	}
	JobType_value = map[string]int32{
		"JOB_TYPE_UNSPECIFIED": 0,
		"JOB_TYPE_HTTP":        1,
		"JOB_TYPE_TCP":         2,
	}
)

func (x JobType) Enum() *JobType {
	p := new(JobType)
	*p = x
	return p
}

func (x JobType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobType) Descriptor() protoreflect.EnumDescriptor {
	return file_private_location_v1_private_location_proto_enumTypes[0].Descriptor()
}

func (JobType) Type() protoreflect.EnumType {
	return &file_private_location_v1_private_location_proto_enumTypes[0]
}

func (x JobType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobType.Descriptor instead.
func (JobType) EnumDescriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{0}
}

type MonitorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorsRequest) Reset() {
	*x = MonitorsRequest{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorsRequest) ProtoMessage() {}

func (x *MonitorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorsRequest.ProtoReflect.Descriptor instead.
func (*MonitorsRequest) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{0}
}

type MonitorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpMonitors  []*HTTPMonitor         `protobuf:"bytes,1,rep,name=http_monitors,json=httpMonitors,proto3" json:"http_monitors,omitempty"`
	TcpMonitors   []*TCPMonitor          `protobuf:"bytes,2,rep,name=tcp_monitors,json=tcpMonitors,proto3" json:"tcp_monitors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonitorsResponse) Reset() {
	*x = MonitorsResponse{}
	mi := &file_private_location_v1_private_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorsResponse) ProtoMessage() {}

func (x *MonitorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_private_location_v1_private_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorsResponse.ProtoReflect.Descriptor instead.
func (*MonitorsResponse) Descriptor() ([]byte, []int) {
	return file_private_location_v1_private_location_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorsResponse) GetHttpMonitors() []*HTTPMonitor {
	if x != nil {
		return x.HttpMonitors
	}
	return nil
}

func (x *MonitorsResponse) GetTcpMonitors() []*TCPMonitor {
	if x != nil {
		return x.TcpMonitors
	}
	return nil
}

var File_private_location_v1_private_location_proto protoreflect.FileDescriptor

const file_private_location_v1_private_location_proto_rawDesc = "" +
	"\n" +
	"*private_location/v1/private_location.proto\x12\x13private_location.v1\x1a&private_location/v1/http_monitor.proto\x1a%private_location/v1/tcp_monitor.proto\"\x11\n" +
	"\x0fMonitorsRequest\"\x9d\x01\n" +
	"\x10MonitorsResponse\x12E\n" +
	"\rhttp_monitors\x18\x01 \x03(\v2 .private_location.v1.HTTPMonitorR\fhttpMonitors\x12B\n" +
	"\ftcp_monitors\x18\x02 \x03(\v2\x1f.private_location.v1.TCPMonitorR\vtcpMonitors*H\n" +
	"\aJobType\x12\x18\n" +
	"\x14JOB_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rJOB_TYPE_HTTP\x10\x01\x12\x10\n" +
	"\fJOB_TYPE_TCP\x10\x022s\n" +
	"\x16PrivateLocationService\x12Y\n" +
	"\bMonitors\x12$.private_location.v1.MonitorsRequest\x1a%.private_location.v1.MonitorsResponse\"\x00BJZHgithub.com/openstatushq/openstatus/packages/proto/private_location/v1;v1b\x06proto3"

var (
	file_private_location_v1_private_location_proto_rawDescOnce sync.Once
	file_private_location_v1_private_location_proto_rawDescData []byte
)

func file_private_location_v1_private_location_proto_rawDescGZIP() []byte {
	file_private_location_v1_private_location_proto_rawDescOnce.Do(func() {
		file_private_location_v1_private_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_private_location_v1_private_location_proto_rawDesc), len(file_private_location_v1_private_location_proto_rawDesc)))
	})
	return file_private_location_v1_private_location_proto_rawDescData
}

var file_private_location_v1_private_location_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_private_location_v1_private_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_private_location_v1_private_location_proto_goTypes = []any{
	(JobType)(0),             // 0: private_location.v1.JobType
	(*MonitorsRequest)(nil),  // 1: private_location.v1.MonitorsRequest
	(*MonitorsResponse)(nil), // 2: private_location.v1.MonitorsResponse
	(*HTTPMonitor)(nil),      // 3: private_location.v1.HTTPMonitor
	(*TCPMonitor)(nil),       // 4: private_location.v1.TCPMonitor
}
var file_private_location_v1_private_location_proto_depIdxs = []int32{
	3, // 0: private_location.v1.MonitorsResponse.http_monitors:type_name -> private_location.v1.HTTPMonitor
	4, // 1: private_location.v1.MonitorsResponse.tcp_monitors:type_name -> private_location.v1.TCPMonitor
	1, // 2: private_location.v1.PrivateLocationService.Monitors:input_type -> private_location.v1.MonitorsRequest
	2, // 3: private_location.v1.PrivateLocationService.Monitors:output_type -> private_location.v1.MonitorsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_private_location_v1_private_location_proto_init() }
func file_private_location_v1_private_location_proto_init() {
	if File_private_location_v1_private_location_proto != nil {
		return
	}
	file_private_location_v1_http_monitor_proto_init()
	file_private_location_v1_tcp_monitor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_private_location_v1_private_location_proto_rawDesc), len(file_private_location_v1_private_location_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_private_location_v1_private_location_proto_goTypes,
		DependencyIndexes: file_private_location_v1_private_location_proto_depIdxs,
		EnumInfos:         file_private_location_v1_private_location_proto_enumTypes,
		MessageInfos:      file_private_location_v1_private_location_proto_msgTypes,
	}.Build()
	File_private_location_v1_private_location_proto = out.File
	file_private_location_v1_private_location_proto_goTypes = nil
	file_private_location_v1_private_location_proto_depIdxs = nil
}
