name: workflows-test
services:
    workflows-test:
        build:
         context: ../..
         dockerfile: apps/workflows/Dockerfile
        env_file:
            - ../../.env.docker

        extra_hosts:
          - "host.docker.internal:host-gateway"

        ports:
            - 3000:3000
            - 8081:8081
        volumes:
            - type: bind
              source: ./data
              target: /app/data
        image: workflows-test
        # command: .
