name: workflows-test
services:
    workflows-test:
        build:
         context: ../..
         dockerfile: apps/workflows/Dockerfile
        environment:
            - DATABASE_URL=http://host.docker.internal:8081
            - DATABASE_AUTH_TOKEN=test
            - RESEND_API_KEY=test
            - UPSTASH_REDIS_REST_URL=test
            - UPSTASH_REDIS_REST_TOKEN=test
            - NODE_ENV=production
            - GCP_PROJECT_ID=test
            - SENTRY_DSN=https://f20616b5573f2a39dab718d99c8d9e38@o4505782661349376.ingest.us.sentry.io/4505782662791168
        extra_hosts:
          - "host.docker.internal:host-gateway"

        ports:
            - 3000:3000
            - 8081:8081
        volumes:
            - type: bind
              source: ./data
              target: /app/data
        image: workflows-test
        # command: .
