export const notificationProvider = [
  "discord",
  "email",
  "google-chat",
  "grafana-oncall",
  "ms-teams",
  "ntfy",
  "pagerduty",
  "opsgenie",
  "slack",
  "sms",
  "telegram",
  "webhook",
  "whatsapp",
  "pushover",
] as const;
