import { db as defaultDb, eq } from "@openstatus/db";
import {
  pageSubscriber,
  selectPageSubscriberSchema,
} from "@openstatus/db/src/schema";
import {
  createSubscription,
  detectWebhookFlavor,
} from "@openstatus/subscriptions";

import { emitAudit } from "../audit";
import { type ServiceContext, withTransaction } from "../context";
import { ValidationError } from "../errors";
import {
  assertSubscribersAllowed,
  loadPageForWorkspace,
  rethrowSubscriptionError,
} from "./internal";
import { CreatePageSubscriberInput } from "./schemas";

export type CreatePageSubscriberResult = { id: number };

/**
 * Create a vendor-added subscription. Skips the verification flow —
 * partner starts receiving notifications immediately. A `token` is still
 * generated by the underlying service so the partner can self-manage via
 * `/manage/{token}` and `/unsubscribe/{token}`.
 *
 * Audit is emitted in the service, not inside the subscriptions package,
 * so there's no circular workspace dependency there.
 */
export async function createPageSubscriber(args: {
  ctx: ServiceContext;
  input: CreatePageSubscriberInput;
}): Promise<CreatePageSubscriberResult> {
  const { ctx } = args;
  const input = CreatePageSubscriberInput.parse(args.input);

  // Per-page workspace + plan check runs in its own tx; the subsequent
  // `createSubscription` call opens its own tx internally in the
  // subscriptions package. We don't try to nest them — the two concerns
  // (authz gate, create) are separately committable and the plan-gate
  // result can't change in the ~microseconds between them.
  //
  // Atomicity trade-off: because `createSubscription` commits its own tx
  // before we get here to emit the audit row, an audit-insert failure
  // below cannot roll back the subscriber row. This inverts the usual
  // "fail-closed audit" guarantee. Threading a tx into the subscriptions
  // package would require widening its public signature across consumers
  // and is deferred. The audit emit is best-effort post-commit; if it
  // fails the caller sees the error but the subscription persists.
  await withTransaction(ctx, async (tx) => {
    const pageWithWorkspace = await loadPageForWorkspace({
      tx,
      pageId: input.pageId,
      workspaceId: ctx.workspace.id,
    });
    assertSubscribersAllowed(pageWithWorkspace);
  });

  // Pre-validate webhook URL flavor here so we surface the same message
  // the legacy router emitted. The subscriptions package re-checks
  // server-side — this is a fast path for caller UX.
  if (
    input.channelType === "webhook" &&
    detectWebhookFlavor(input.webhookUrl) === "generic"
  ) {
    throw new ValidationError(
      "Only Slack and Discord webhook URLs are supported.",
    );
  }

  let subscriptionId: number;
  try {
    const subscription =
      input.channelType === "email"
        ? await createSubscription({
            pageId: input.pageId,
            channelType: "email",
            email: input.email,
            name: input.name ?? null,
            componentIds: input.componentIds,
          })
        : await createSubscription({
            pageId: input.pageId,
            channelType: "webhook",
            webhookUrl: input.webhookUrl,
            name: input.name ?? null,
            channelConfig: input.headers
              ? { headers: input.headers }
              : undefined,
            componentIds: input.componentIds,
          });
    subscriptionId = subscription.id;
  } catch (error) {
    // `rethrowSubscriptionError` is `: never` but tsc can't always trace
    // that through the dynamic import path, so the catch sits flat
    // alongside the audit emit rather than wrapping it.
    rethrowSubscriptionError(error);
  }

  // Snapshot the freshly-inserted row for the audit entry. Strip the
  // management `token` — it's the capability for the self-manage /
  // unsubscribe URLs and must never land in the audit log. Runs
  // outside the subscriptions package's tx (already committed), using
  // a fresh query to avoid widening the subscriptions return shape.
  const db = ctx.db ?? defaultDb;
  const row = await db.query.pageSubscriber.findFirst({
    where: eq(pageSubscriber.id, subscriptionId),
  });
  if (row) {
    const parsed = selectPageSubscriberSchema.parse(row);
    const { token: _token, ...after } = parsed;
    await withTransaction(ctx, async (tx) => {
      await emitAudit(tx, ctx, {
        action: "page_subscriber.create",
        entityType: "page_subscriber",
        entityId: parsed.id,
        after,
        metadata: input.componentIds?.length
          ? { componentIds: input.componentIds }
          : undefined,
      });
    });
  }

  return { id: subscriptionId };
}
