import type { InferInsertModel } from "drizzle-orm";
import type { externalService } from "../schema";

type ExternalServiceSeedEntry = InferInsertModel<typeof externalService>;

export const externalServicesSeed: ExternalServiceSeedEntry[] = [
  {
    slug: "github",
    name: "GitHub",
    url: "https://github.com",
    statusPageUrl: "https://www.githubstatus.com",
    provider: "atlassian-statuspage",
    industry: ["development-tools"],
    description: "The world's leading software development platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "vercel",
    name: "Vercel",
    url: "https://vercel.com",
    statusPageUrl: "https://www.vercel-status.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers", "development-tools"],
    description: "Platform for frontend developers",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "slack",
    name: "Slack",
    url: "https://slack.com",
    statusPageUrl: "https://slack-status.com",
    provider: "custom",
    industry: ["communication"],
    description: "Team collaboration and messaging platform",
    apiConfig: {
      type: "custom",
      endpoint: "https://slack-status.com/api/v2.0.0/current",
      parser: "slack",
    },
  },
  {
    slug: "openai",
    name: "OpenAI",
    url: "https://openai.com",
    statusPageUrl: "https://status.openai.com",
    provider: "atlassian-statuspage",
    industry: ["ai-ml"],
    description: "AI research and deployment company",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    url: "https://www.anthropic.com",
    statusPageUrl: "https://status.anthropic.com",
    provider: "atlassian-statuspage",
    industry: ["ai-ml"],
    description: "AI safety company building reliable, interpretable AI systems",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    url: "https://cloudflare.com",
    statusPageUrl: "https://www.cloudflarestatus.com",
    provider: "atlassian-statuspage",
    industry: ["cdn", "security"],
    description: "Web infrastructure and security company",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "atlassian",
    name: "Atlassian",
    url: "https://www.atlassian.com",
    statusPageUrl: "https://status.atlassian.com",
    provider: "atlassian-statuspage",
    industry: ["saas", "development-tools"],
    description: "Maker of Jira, Confluence, Bitbucket, and Statuspage",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "digitalocean",
    name: "DigitalOcean",
    url: "https://www.digitalocean.com",
    statusPageUrl: "https://status.digitalocean.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers"],
    description: "Cloud infrastructure for developers",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "discord",
    name: "Discord",
    url: "https://discord.com",
    statusPageUrl: "https://discordstatus.com",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Voice, video, and text communication for communities",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "mongodb-atlas",
    name: "MongoDB Atlas",
    url: "https://www.mongodb.com",
    statusPageUrl: "https://status.mongodb.com",
    provider: "atlassian-statuspage",
    industry: ["databases"],
    description: "Multi-cloud database service for modern applications",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "npm",
    name: "npm",
    url: "https://www.npmjs.com",
    statusPageUrl: "https://status.npmjs.org",
    provider: "atlassian-statuspage",
    industry: ["development-tools"],
    description: "JavaScript package registry",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "reddit",
    name: "Reddit",
    url: "https://www.reddit.com",
    statusPageUrl: "https://www.redditstatus.com",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Network of communities based on people's interests",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "supabase",
    name: "Supabase",
    url: "https://supabase.com",
    statusPageUrl: "https://status.supabase.com",
    provider: "atlassian-statuspage",
    industry: ["databases", "development-tools"],
    description: "Open-source Firebase alternative",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "twilio",
    name: "Twilio",
    url: "https://www.twilio.com",
    statusPageUrl: "https://status.twilio.com",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Cloud communications platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "zoom",
    name: "Zoom",
    url: "https://zoom.us",
    statusPageUrl: "https://status.zoom.us",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Video conferencing platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "datadog",
    name: "Datadog",
    url: "https://www.datadoghq.com",
    statusPageUrl: "https://status.datadoghq.com",
    provider: "atlassian-statuspage",
    industry: ["monitoring"],
    description: "Monitoring and analytics for cloud-scale applications",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "cloudflare-workers",
    name: "Cloudflare Workers",
    url: "https://workers.cloudflare.com",
    statusPageUrl: "https://www.cloudflarestatus.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers", "cdn"],
    description: "Serverless platform at the edge",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "shopify",
    name: "Shopify",
    url: "https://www.shopify.com",
    statusPageUrl: "https://www.shopifystatus.com",
    provider: "atlassian-statuspage",
    industry: ["e-commerce"],
    description: "E-commerce platform for online stores",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "1password",
    name: "1Password",
    url: "https://1password.com",
    statusPageUrl: "https://status.1password.com",
    provider: "atlassian-statuspage",
    industry: ["security", "saas"],
    description: "Password manager for individuals, families, and teams",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "airtable",
    name: "Airtable",
    url: "https://www.airtable.com",
    statusPageUrl: "https://status.airtable.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Cloud-based collaboration platform combining databases and spreadsheets",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "amplitude",
    name: "Amplitude",
    url: "https://amplitude.com",
    statusPageUrl: "https://status.amplitude.com",
    provider: "atlassian-statuspage",
    industry: ["monitoring"],
    description: "Product analytics platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "appsflyer",
    name: "AppsFlyer",
    url: "https://www.appsflyer.com",
    statusPageUrl: "https://status.appsflyer.com",
    provider: "atlassian-statuspage",
    industry: ["monitoring"],
    description: "Mobile attribution and marketing analytics platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "bitbucket",
    name: "Bitbucket",
    url: "https://bitbucket.org",
    statusPageUrl: "https://bitbucket.status.atlassian.com",
    provider: "atlassian-statuspage",
    industry: ["development-tools"],
    description: "Git code hosting for teams",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "bitly",
    name: "Bitly",
    url: "https://bitly.com",
    statusPageUrl: "https://status.bitly.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Link management and URL shortening platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "box",
    name: "Box",
    url: "https://www.box.com",
    statusPageUrl: "https://status.box.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Cloud content management and file sharing",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "circleci",
    name: "CircleCI",
    url: "https://circleci.com",
    statusPageUrl: "https://status.circleci.com",
    provider: "atlassian-statuspage",
    industry: ["development-tools"],
    description: "Continuous integration and delivery platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "cloudinary",
    name: "Cloudinary",
    url: "https://cloudinary.com",
    statusPageUrl: "https://status.cloudinary.com",
    provider: "atlassian-statuspage",
    industry: ["cdn", "development-tools"],
    description: "Image and video management cloud service",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "cloudways",
    name: "Cloudways",
    url: "https://www.cloudways.com",
    statusPageUrl: "https://status.cloudways.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers"],
    description: "Managed cloud hosting platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "coinbase",
    name: "Coinbase",
    url: "https://www.coinbase.com",
    statusPageUrl: "https://status.coinbase.com",
    provider: "atlassian-statuspage",
    industry: ["fintech"],
    description: "Cryptocurrency exchange platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "coursera",
    name: "Coursera",
    url: "https://www.coursera.org",
    statusPageUrl: "https://status.coursera.org",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Online learning platform with courses from universities and companies",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "crowdin",
    name: "Crowdin",
    url: "https://crowdin.com",
    statusPageUrl: "https://status.crowdin.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Localization management platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "dropbox",
    name: "Dropbox",
    url: "https://www.dropbox.com",
    statusPageUrl: "https://status.dropbox.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Cloud file storage and collaboration",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "epic-games",
    name: "Epic Games",
    url: "https://www.epicgames.com",
    statusPageUrl: "https://status.epicgames.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Game developer and publisher, maker of Fortnite and Unreal Engine",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "figma",
    name: "Figma",
    url: "https://www.figma.com",
    statusPageUrl: "https://status.figma.com",
    provider: "atlassian-statuspage",
    industry: ["saas", "development-tools"],
    description: "Collaborative interface design tool",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "fivetran",
    name: "Fivetran",
    url: "https://www.fivetran.com",
    statusPageUrl: "https://status.fivetran.com",
    provider: "atlassian-statuspage",
    industry: ["databases", "development-tools"],
    description: "Automated data integration and ELT pipelines",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "grammarly",
    name: "Grammarly",
    url: "https://www.grammarly.com",
    statusPageUrl: "https://status.grammarly.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "AI writing assistant for grammar and style",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "greenhouse",
    name: "Greenhouse",
    url: "https://www.greenhouse.io",
    statusPageUrl: "https://status.greenhouse.io",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Recruiting and applicant tracking platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "hostinger",
    name: "Hostinger",
    url: "https://www.hostinger.com",
    statusPageUrl: "https://statuspage.hostinger.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers"],
    description: "Web hosting and domain provider",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "hubspot",
    name: "HubSpot",
    url: "https://www.hubspot.com",
    statusPageUrl: "https://status.hubspot.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "CRM, marketing, sales, and service platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "jamf",
    name: "Jamf",
    url: "https://www.jamf.com",
    statusPageUrl: "https://status.jamf.com",
    provider: "atlassian-statuspage",
    industry: ["security", "saas"],
    description: "Apple device management for enterprise",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "kinsta",
    name: "Kinsta",
    url: "https://kinsta.com",
    statusPageUrl: "https://status.kinsta.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers"],
    description: "Managed WordPress and application hosting",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "lastpass",
    name: "LastPass",
    url: "https://www.lastpass.com",
    statusPageUrl: "https://status.lastpass.com",
    provider: "atlassian-statuspage",
    industry: ["security", "saas"],
    description: "Password manager and identity service",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "launchdarkly",
    name: "LaunchDarkly",
    url: "https://launchdarkly.com",
    statusPageUrl: "https://status.launchdarkly.com",
    provider: "atlassian-statuspage",
    industry: ["development-tools"],
    description: "Feature flag and experimentation platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "lever",
    name: "Lever",
    url: "https://www.lever.co",
    statusPageUrl: "https://status.lever.co",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Talent acquisition and applicant tracking suite",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "linear",
    name: "Linear",
    url: "https://linear.app",
    statusPageUrl: "https://linearstatus.com",
    provider: "atlassian-statuspage",
    industry: ["saas", "development-tools"],
    description: "Issue tracking and project management for software teams",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "linode",
    name: "Linode",
    url: "https://www.linode.com",
    statusPageUrl: "https://status.linode.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers"],
    description: "Cloud computing and Linux virtual servers",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "loom",
    name: "Loom",
    url: "https://www.loom.com",
    statusPageUrl: "https://status.loom.com",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Async video messaging for work",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "mezmo",
    name: "Mezmo",
    url: "https://www.mezmo.com",
    statusPageUrl: "https://status.mezmo.com",
    provider: "atlassian-statuspage",
    industry: ["monitoring"],
    description: "Observability pipeline for logs and telemetry",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "mixpanel",
    name: "Mixpanel",
    url: "https://mixpanel.com",
    statusPageUrl: "https://status.mixpanel.com",
    provider: "atlassian-statuspage",
    industry: ["monitoring"],
    description: "Product analytics for user behavior",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "netlify",
    name: "Netlify",
    url: "https://www.netlify.com",
    statusPageUrl: "https://www.netlifystatus.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers", "development-tools"],
    description: "Web platform for building and deploying modern sites",
    apiConfig: { type: "atlassian" },
  },

  {
    slug: "postman",
    name: "Postman",
    url: "https://www.postman.com",
    statusPageUrl: "https://status.postman.com",
    provider: "atlassian-statuspage",
    industry: ["development-tools"],
    description: "API development and testing platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "render",
    name: "Render",
    url: "https://render.com",
    statusPageUrl: "https://status.render.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers"],
    description: "Cloud platform for hosting web apps and services",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "scaleway",
    name: "Scaleway",
    url: "https://www.scaleway.com",
    statusPageUrl: "https://status.scaleway.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers"],
    description: "European cloud infrastructure provider",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "segment",
    name: "Segment",
    url: "https://segment.com",
    statusPageUrl: "https://status.segment.com",
    provider: "atlassian-statuspage",
    industry: ["development-tools"],
    description: "Customer data platform and event routing",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "sendgrid",
    name: "SendGrid",
    url: "https://sendgrid.com",
    statusPageUrl: "https://status.sendgrid.com",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Transactional and marketing email API",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "sentry",
    name: "Sentry",
    url: "https://sentry.io",
    statusPageUrl: "https://status.sentry.io",
    provider: "atlassian-statuspage",
    industry: ["monitoring", "development-tools"],
    description: "Application error monitoring and performance tracing",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "snowflake",
    name: "Snowflake",
    url: "https://www.snowflake.com",
    statusPageUrl: "https://status.snowflake.com",
    provider: "atlassian-statuspage",
    industry: ["databases"],
    description: "Cloud data platform for analytics and warehousing",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "snyk",
    name: "Snyk",
    url: "https://snyk.io",
    statusPageUrl: "https://status.snyk.io",
    provider: "atlassian-statuspage",
    industry: ["security", "development-tools"],
    description: "Developer security platform for code, dependencies, and containers",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "squarespace",
    name: "Squarespace",
    url: "https://www.squarespace.com",
    statusPageUrl: "https://status.squarespace.com",
    provider: "atlassian-statuspage",
    industry: ["saas", "e-commerce"],
    description: "Website builder and online store platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "sumo-logic",
    name: "Sumo Logic",
    url: "https://www.sumologic.com",
    statusPageUrl: "https://status.sumologic.com",
    provider: "atlassian-statuspage",
    industry: ["monitoring"],
    description: "Cloud log management and security analytics",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "teamviewer",
    name: "TeamViewer",
    url: "https://www.teamviewer.com",
    statusPageUrl: "https://status.teamviewer.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Remote desktop and remote support software",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "trello",
    name: "Trello",
    url: "https://trello.com",
    statusPageUrl: "https://trello.status.atlassian.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Kanban-style project management tool",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "udemy",
    name: "Udemy",
    url: "https://www.udemy.com",
    statusPageUrl: "https://status.udemy.com",
    provider: "atlassian-statuspage",
    industry: ["saas"],
    description: "Online learning and teaching marketplace",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "upcloud",
    name: "UpCloud",
    url: "https://upcloud.com",
    statusPageUrl: "https://status.upcloud.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers"],
    description: "European cloud server provider",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "vimeo",
    name: "Vimeo",
    url: "https://vimeo.com",
    statusPageUrl: "https://status.vimeo.com",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Video hosting, sharing, and streaming platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "webflow",
    name: "Webflow",
    url: "https://webflow.com",
    statusPageUrl: "https://status.webflow.com",
    provider: "atlassian-statuspage",
    industry: ["saas", "development-tools"],
    description: "Visual web design and CMS platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "wix",
    name: "Wix",
    url: "https://www.wix.com",
    statusPageUrl: "https://status.wix.com",
    provider: "atlassian-statuspage",
    industry: ["saas", "e-commerce"],
    description: "Website builder and business platform",
    apiConfig: { type: "atlassian" },
  },
];
