import type { InferInsertModel } from "drizzle-orm";
import type { externalService } from "../schema";

type ExternalServiceSeedEntry = InferInsertModel<typeof externalService>;

export const externalServicesSeed: ExternalServiceSeedEntry[] = [
  {
    slug: "github",
    name: "GitHub",
    url: "https://github.com",
    statusPageUrl: "https://www.githubstatus.com",
    provider: "atlassian-statuspage",
    industry: ["development-tools"],
    description: "The world's leading software development platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "vercel",
    name: "Vercel",
    url: "https://vercel.com",
    statusPageUrl: "https://www.vercel-status.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers", "development-tools"],
    description: "Platform for frontend developers",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "slack",
    name: "Slack",
    url: "https://slack.com",
    statusPageUrl: "https://slack-status.com",
    provider: "custom",
    industry: ["communication"],
    description: "Team collaboration and messaging platform",
    apiConfig: {
      type: "custom",
      endpoint: "https://slack-status.com/api/v2.0.0/current",
      parser: "slack",
    },
  },
  {
    slug: "openai",
    name: "OpenAI",
    url: "https://openai.com",
    statusPageUrl: "https://status.openai.com",
    provider: "atlassian-statuspage",
    industry: ["ai-ml"],
    description: "AI research and deployment company",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    url: "https://www.anthropic.com",
    statusPageUrl: "https://status.anthropic.com",
    provider: "atlassian-statuspage",
    industry: ["ai-ml"],
    description:
      "AI safety company building reliable, interpretable AI systems",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "cloudflare",
    name: "Cloudflare",
    url: "https://cloudflare.com",
    statusPageUrl: "https://www.cloudflarestatus.com",
    provider: "atlassian-statuspage",
    industry: ["cdn", "security"],
    description: "Web infrastructure and security company",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "atlassian",
    name: "Atlassian",
    url: "https://www.atlassian.com",
    statusPageUrl: "https://status.atlassian.com",
    provider: "atlassian-statuspage",
    industry: ["saas", "development-tools"],
    description: "Maker of Jira, Confluence, Bitbucket, and Statuspage",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "digitalocean",
    name: "DigitalOcean",
    url: "https://www.digitalocean.com",
    statusPageUrl: "https://status.digitalocean.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers"],
    description: "Cloud infrastructure for developers",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "discord",
    name: "Discord",
    url: "https://discord.com",
    statusPageUrl: "https://discordstatus.com",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Voice, video, and text communication for communities",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "mongodb-atlas",
    name: "MongoDB Atlas",
    url: "https://www.mongodb.com",
    statusPageUrl: "https://status.mongodb.com",
    provider: "atlassian-statuspage",
    industry: ["databases"],
    description: "Multi-cloud database service for modern applications",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "npm",
    name: "npm",
    url: "https://www.npmjs.com",
    statusPageUrl: "https://status.npmjs.org",
    provider: "atlassian-statuspage",
    industry: ["development-tools"],
    description: "JavaScript package registry",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "reddit",
    name: "Reddit",
    url: "https://www.reddit.com",
    statusPageUrl: "https://www.redditstatus.com",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Network of communities based on people's interests",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "supabase",
    name: "Supabase",
    url: "https://supabase.com",
    statusPageUrl: "https://status.supabase.com",
    provider: "atlassian-statuspage",
    industry: ["databases", "development-tools"],
    description: "Open-source Firebase alternative",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "twilio",
    name: "Twilio",
    url: "https://www.twilio.com",
    statusPageUrl: "https://status.twilio.com",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Cloud communications platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "zoom",
    name: "Zoom",
    url: "https://zoom.us",
    statusPageUrl: "https://status.zoom.us",
    provider: "atlassian-statuspage",
    industry: ["communication"],
    description: "Video conferencing platform",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "datadog",
    name: "Datadog",
    url: "https://www.datadoghq.com",
    statusPageUrl: "https://status.datadoghq.com",
    provider: "atlassian-statuspage",
    industry: ["monitoring"],
    description: "Monitoring and analytics for cloud-scale applications",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "cloudflare-workers",
    name: "Cloudflare Workers",
    url: "https://workers.cloudflare.com",
    statusPageUrl: "https://www.cloudflarestatus.com",
    provider: "atlassian-statuspage",
    industry: ["cloud-providers", "cdn"],
    description: "Serverless platform at the edge",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "shopify",
    name: "Shopify",
    url: "https://www.shopify.com",
    statusPageUrl: "https://www.shopifystatus.com",
    provider: "atlassian-statuspage",
    industry: ["e-commerce"],
    description: "E-commerce platform for online stores",
    apiConfig: { type: "atlassian" },
  },
  {
    slug: "bluesky",
    name: "Bluesky",
    url: "https://bsky.app",
    statusPageUrl: "https://status.bsky.app",
    provider: "uptime-robot",
    industry: ["communication"],
    description: "Decentralized social network built on the AT Protocol",
    apiConfig: {
      type: "uptimerobot",
      endpoint: "https://status.bsky.app/api/getMonitorList/2102707-357837",
    },
  },
];
