import type { Region } from "../types";

// https://fly.io/docs/reference/regions/
export const regions: Record<string, Region> = {
  ams: { code: "ams", location: "Amsterdam, Netherlands", flag: "🇳🇱" },
  arn: { code: "arn", location: "Stockholm, Sweden", flag: "🇸🇪" },
  atl: { code: "atl", location: "Atlanta, Georgia (US)", flag: "🇺🇸" },
  bog: { code: "bog", location: "Bogotá, Colombia", flag: "🇨🇴" },
  bom: { code: "bom", location: "Mumbai, India", flag: "🇮🇳" },
  bos: { code: "bos", location: "Boston, Massachusetts (US)", flag: "🇺🇸" },
  cdg: { code: "cdg", location: "Paris, France", flag: "🇫🇷" },
  den: { code: "den", location: "Denver, Colorado (US)", flag: "🇺🇸" },
  dfw: { code: "dfw", location: "Dallas, Texas (US)", flag: "🇺🇸" },
  ewr: { code: "ewr", location: "Secaucus, NJ (US)", flag: "🇺🇸" },
  eze: { code: "eze", location: "Ezeiza, Argentina", flag: "🇦🇷" },
  fra: { code: "fra", location: "Frankfurt, Germany", flag: "🇩🇪" },
  gdl: { code: "gdl", location: "Guadalajara, Mexico", flag: "🇲🇽" },
  gig: { code: "gig", location: "Rio de Janeiro, Brazil", flag: "🇧🇷" },
  gru: { code: "gru", location: "Sao Paulo, Brazil", flag: "🇧🇷" },
  hkg: { code: "hkg", location: "Hong Kong, Hong Kong", flag: "🇭🇰" },
  iad: { code: "iad", location: "Ashburn, Virginia (US)", flag: "🇺🇸" },
  jnb: { code: "jnb", location: "Johannesburg, South Africa", flag: "🇿🇦" },
  lax: { code: "lax", location: "Los Angeles, California (US)", flag: "🇺🇸" },
  lhr: { code: "lhr", location: "London, United Kingdom", flag: "🇬🇧" },
  mad: { code: "mad", location: "Madrid, Spain", flag: "🇪🇸" },
  mia: { code: "mia", location: "Miami, Florida (US)", flag: "🇺🇸" },
  nrt: { code: "nrt", location: "Tokyo, Japan", flag: "🇯🇵" },
  ord: { code: "ord", location: "Chicago, Illinois (US)", flag: "🇺🇸" },
  otp: { code: "otp", location: "Bucharest, Romania", flag: "🇷🇴" },
  phx: { code: "phx", location: "Phoenix, Arizona (US)", flag: "🇺🇸" },
  qro: { code: "qro", location: "Querétaro, Mexico", flag: "🇲🇽" },
  scl: { code: "scl", location: "Santiago, Chile", flag: "🇨🇱" },
  sea: { code: "sea", location: "Seattle, Washington (US)", flag: "🇺🇸" },
  sin: { code: "sin", location: "Singapore, Singapore", flag: "🇸🇬" },
  sjc: { code: "sjc", location: "San Jose, California (US)", flag: "🇺🇸" },
  syd: { code: "syd", location: "Sydney, Australia", flag: "🇦🇺" },
  waw: { code: "waw", location: "Warsaw, Poland", flag: "🇵🇱" },
  yul: { code: "yul", location: "Montreal, Canada", flag: "🇨🇦" },
  yyz: { code: "yyz", location: "Toronto, Canada", flag: "🇨🇦" },
};
