name: Check
on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]

jobs:
  check:
    name: 🔍 Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: ⎔ Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: 📥 Download deps
        run: pnpm install

      - name: 🔍 Check
        run: pnpm check
