name: Go Tests

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - '**'
    paths:
      - "apps/checker/**"
      - "apps/private-location/**"

jobs:
  ci:
    name: Continuous Integration
    runs-on: depot-ubuntu-24.04-4
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.25.0'
      - name: Run test Checker
        run: go test -timeout 30s -race -count=1 ./...
        working-directory: apps/checker
      - name: Run test Private Location
        run: go test -timeout 30s -race -count=1 ./...
        working-directory: apps/private-location
