name: Publish Checker
on:
  push:
    branches:
      - main
    paths:
      - "apps/checker/**"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: checker

jobs:
  build-checker:
    runs-on: ubuntu-latest
    # Permissions to use OIDC token authentication
    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          project: 9cknw183m8
          context: apps/checker
          tags: ghcr.io/openstatushq/checker:latest
          platforms: linux/amd64,linux/arm64
          push: true
  build-private-location:
    runs-on: ubuntu-latest
    # Permissions to use OIDC token authentication
    permissions:
      contents: read
      id-token: write
      # Allows pushing to the GitHub Container Registry
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          file: private-location.Dockerfile
          project: 9cknw183m8
          context: apps/checker
          tags: ghcr.io/openstatushq/private-location:latest
          platforms: linux/amd64,linux/arm64
          push: true
