name: Run OpenStatus Synthetics CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  synthetic_ci:
    runs-on: ubuntu-latest
    name: Run OpenStatus Synthetics CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run OpenStatus Synthetics CI
        uses: openstatushq/openstatus-github-action@v1
        with:
          api_key: ${{ secrets.OPENSTATUS_API_KEY }}
